# Generated by Django 3.2.12 on 2022-04-25 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_thrones', '0003_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_anon',
            field=models.BooleanField(default=True),
        ),
    ]
